is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^(r|s|d|t|z)i?(view|g?(vim|fvim|nvim|\.nvim-wrapped)(diff)?)$'"

bind-key -n C-h run-shell "$is_vim && tmux send-keys C-h || tmux select-pane -L"
bind-key -n C-j run-shell "$is_vim && tmux send-keys C-j || tmux select-pane -D"
bind-key -n C-k run-shell "$is_vim && tmux send-keys C-k || tmux select-pane -U"
bind-key -n C-l run-shell "$is_vim && tmux send-keys C-l || tmux select-pane -R"
bind-key -n C-S-\\ run-shell "$is_vim && tmux send-keys C-\\ || tmux select-pane -l"
