#!/bin/bash

# In Rainbows accent color (orange)
COLOR=0xFFF25A16

PLUGIN_DIR="$HOME/.config/sketchybar/scripts"

sketchybar --bar height=54        \
                 margin=12        \
                 y_offset=0       \
                 padding_left=0   \
                 padding_right=0  \
                 color=0x00000000

sketchybar --default updates=when_shown                             \
                     icon.font="Hack Nerd Font:Regular:12"          \
                     icon.color=0xFFFFFFFF                          \
                     label.font="Hack Nerd Font:Regular:12"         \
                     background.color=0x00000000                    \
                     y_offset=0

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
SPACES=()

for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  SPACES+=(space.$sid)
  sketchybar --add space space.$sid left \
             --set space.$sid associated_space=$sid \
                              icon=${SPACE_ICONS[i]} \
                              icon.highlight_color=0xFFFFFFFF \
                              icon.align=center \
                              icon.width=30 \
                              label.drawing=off \
                              click_script="aerospace workspace $sid"
done

sketchybar --add bracket spaces '/space\..*/'                      \
           --set         spaces background.color=0xEB1e1e2e        \
                                background.border_width=1          \
                                background.border_color=$COLOR     \
                                blur_radius=2                      \
                                background.height=30

# MPD Now Playing widget with album art
sketchybar --add item music left                                   \
           --set      music icon="󰎆"                               \
                            icon.color=$COLOR                      \
                            icon.background.drawing=off            \
                            icon.background.image.scale=0.034      \
                            label="Not Playing"                    \
                            drawing=on                             \
                            background.color=0xEB1e1e2e            \
                            background.border_width=1              \
                            background.border_color=$COLOR         \
                            background.height=30                   \
                            blur_radius=2                          \
                            icon.padding_left=14                   \
                            icon.padding_right=10                  \
                            label.padding_left=0                   \
                            label.padding_right=12                 \
                            background.padding_left=18             \
                            script="$PLUGIN_DIR/music.sh"          \
                            update_freq=1                          \
           --subscribe music system_woke

sketchybar --default                                                \
                     background.color=0xEB1e1e2e                    \
                     blur_radius=2                                  \
                     background.height=30                           \
                     icon.padding_left=12                           \
                     icon.padding_right=4                           \
                     label.padding_left=4                           \
                     label.padding_right=12                         \
                     background.padding_left=18                     \
                     background.border_width=1

sketchybar --add item time right                                    \
           --set      time icon=󱑎                                   \
                           icon.color=$COLOR                       \
                           background.border_color=$COLOR          \
                           label="$(date '+%I:%M %p')"              \
                           script="$PLUGIN_DIR/time.sh"             \
                           update_freq=1

sketchybar --add item date right                                    \
           --set      date icon=󱨰                                   \
                           icon.color=$COLOR                       \
                           background.border_color=$COLOR          \
                           label="$(date '+%a %b %d')"              \
                           script="$PLUGIN_DIR/date.sh"             \
                           update_freq=10

sketchybar --add item battery right                                 \
           --set      battery icon=                                \
                              icon.color=$COLOR                    \
                              background.border_color=$COLOR       \
                              label="--%"                           \
                              script="$PLUGIN_DIR/battery.sh"       \
                              update_freq=20

sketchybar --hotload on
sketchybar --update
