music_directory "/Users/mira/Music/Stash"

playlist_directory "/Users/mira/.local/share/mpd/playlists"
db_file "/Users/mira/.local/share/mpd/mpd.db"

bind_to_address "127.0.0.1"
port "6600"
state_file "/Users/mira/.local/share/mpd/state"
metadata_to_use "artist,album,title,track"
auto_update "yes"

audio_output {
  type "osx"
  name "CoreAudio"
  mixer_type "software"
}

audio_output {
  type "fifo"
  name "Visualizer"
  path "/tmp/mpd.fifo"
  format "44100:16:2"
}
