music_directory "/Users/mira/Music/Stash"

playlist_directory "/Users/mira/.local/share/mpd/playlists"
db_file "/Users/mira/.local/share/mpd/mpd.db"

bind_to_address "127.0.0.1"
port "6600"

metadata_to_use "artist,album,title,track"
auto_update "yes"
